compile:
		clear
# g++ binarySearchTree.cpp -o binary.out
		g++ T1.cpp binarySearchTree.cpp -o binary1.out
		g++ T3.cpp binarySearchTree.cpp -o binary2.out
		g++ T4.cpp binarySearchTree.cpp -o binary3.out
		g++ T8.cpp binarySearchTree.cpp -o binary4.out
		g++ T9.cpp binarySearchTree.cpp -o binary5.out
		g++ T10.cpp binarySearchTree.cpp -o binary6.out
		g++ T12.cpp binarySearchTree.cpp -o binary7.out
		g++ T14.cpp binarySearchTree.cpp -o binary8.out
		g++ T15.cpp binarySearchTree.cpp -o binary9.out
		g++ T16.cpp binarySearchTree.cpp -o binary10.out
		g++ T18.cpp binarySearchTree.cpp -o binary11.out

run:
# ./binary.out
		./binary1.out
		./binary2.out
		./binary3.out
		./binary4.out
		./binary5.out
		./binary6.out
		./binary7.out
		./binary8.out
		./binary9.out
		./binary10.out
		./binary11.out
clean:
		rm *.out
both: compile run clean
