compile:
	clear
	g++ T6.cpp infixToPostfix.cpp -o lab.out
run: 
	./lab.out
clean:
	rm *.out
both: compile run
testall: 
	clear
	g++ T1.cpp infixToPostfix.cpp -o lab.out
	./lab.out

	g++ T2.cpp infixToPostfix.cpp -o lab.out
	./lab.out

	g++ T3.cpp infixToPostfix.cpp -o lab.out
	./lab.out
	
	g++ T4.cpp infixToPostfix.cpp -o lab.out
	./lab.out
	
	g++ T5.cpp infixToPostfix.cpp -o lab.out
	./lab.out
	
	g++ T6.cpp infixToPostfix.cpp -o lab.out
	./lab.out

	g++ T8.cpp infixToPostfix.cpp -o lab.out
	./lab.out
	
	g++ T9.cpp infixToPostfix.cpp -o lab.out
	./lab.out
	
	g++ T11.cpp infixToPostfix.cpp -o lab.out
	./lab.out

	g++ T16.cpp infixToPostfix.cpp -o lab.out
	./lab.out
	
	g++ T17.cpp infixToPostfix.cpp -o lab.out
	./lab.out
	
	g++ T18.cpp infixToPostfix.cpp -o lab.out
	./lab.out

	g++ T19.cpp infixToPostfix.cpp -o lab.out
	./lab.out